name: start or stop azure virtual machine
on:
  workflow_dispatch:
    inputs:
      action:
        default: "stop"
        required: true
        type: choice
        options:
          - start
          - stop
      vm_name:
        required: true
        default: "devwithkrishna-vm"
        type: string
      resource_group:
        required: true
        default: "DEV-WITH-KRISHNA-VM-RG"
        type: string
      resource_provider_string:
        required: true
        default: "providers/Microsoft.Compute/virtualMachines"
        type: string
jobs:
  start-or-stop-azure-virtual-machine:
    runs-on: ubuntu-latest  
    name: ${{ github.actor }} ${{ github.events.inputs.action }} ${{github.events.inputs.vm_name}} VM  
    steps:
    - name: echo inputs
      run: |
        echo " action ${{github.event.inputs.action}} vmname ${{github.event.inputs.vm_name}} "
